#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|release|hotfix)\/([A-Z]+-[0-9]+)/[a-z0-9._-]+$"

message="There is something wrong with your branch name.
Branch names in this project must adhere to this contract: $valid_branch_regex. 
Your commit will be rejected. You should rename your branch to a valid name and try again.
The valid branch name example is: { feature | bugfix | release } / {Ticket #} / <brief-description-upto-five-words>'

Steps to rename the Branch name:

A. on Remote
    1. git push origin --delete old-branch-name
    2. git push origin -u new-branch-name
B. on Local
    git branch -m new-branch-name
"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0

