name: Astronomer CI - Deploy code

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
  BASE_DOMAIN: astronomer-airflow.st.dev
  RELEASE_NAME: testing-harut

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: registry.${{ env.BASE_DOMAIN }}
        username: _
        password: ${{ env.ASTRONOMER_KEY_SECRET }}
    - name: Build image
      run: docker build -t registry.${{ env.BASE_DOMAIN }}/${{ env.RELEASE_NAME }}/airflow:ci-${{ github.sha }} .
    - name: Push image
      run: docker push registry.${{ env.BASE_DOMAIN }}/${{ env.RELEASE_NAME }}/airflow:ci-${{ github.sha }}